kind: wasmer.io/App.v0

name: chatroom
owner: wj6010

env:
  PORT: "8080"
  DATABASE_PATH: "./chat.db"

redirect:
  force_https: true

health_checks:
  - http:
      method: get
      path: /login
      interval: 30s
      timeout: 10s
      unhealthy_threshold: 3
      healthy_threshold: 1
      expected_status_codes:
        - 200
